version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.15

executors:
  node:
    docker:
      - image: circleci/node:10

jobs:
  build_and_deploy:
    executor: node
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - checkout
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          aws-region: AWS_REGION
          from: ./build
          overwrite: true
          to: "s3://front-ci-test"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_deploy
  # test:
  #  executor: node
  #  steps:
  #    - checkout
  #    - run: npm install
  #    - run: npm run test
